smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -258,18 +258,28 @@ jobs:
       - run:
           name: Backend smoke test.
           command: |
-            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            
-            URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
-            # URL="http://mohamedlotfy45.com"
-            if curl -s --head ${URL}
+            URL="http://udapeople-789bbc4.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
             then
-              echo "It worked!"
-              exit 0
+            # Change this to 0 after the job fails
+            return 0
             else
-              echo "Rolling Back"
-              exit 1
+            return 1
             fi
+
+            # export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            
+            # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            # # URL="http://mohamedlotfy45.com"
+            # if curl -s --head ${URL}
+            # then
+            #   echo "It worked!"
+            #   exit 0
+            # else
+            #   echo "Rolling Back"
+            #   exit 1
+            # fi
       
 #       # Here's where you will add some code to rollback on failure  
 
