cloud front

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -250,52 +250,51 @@ jobs:
   #           ansible-playbook -i inventory.txt deploy-backend.yml
 #       # Here's where you will add some code to rollback on failure  
 
-  smoke-test:
-    docker:
-      - image: amazon/aws-cli 
-    steps:
-      - checkout
-      - run:
-          name: Backend smoke test.
-          command: |
-            URL="http://udapeople-789bbc4.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-            # Change this to 0 after the job fails
-            return 0
-            else
-            return 1
-            fi
+  # smoke-test:
+  #   docker:
+  #     - image: amazon/aws-cli 
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Backend smoke test.
+  #         command: |
+  #           URL="http://udapeople-789bbc4.s3-website-us-east-1.amazonaws.com/#/employees"            
+  #           echo ${URL} 
+  #           if curl -s ${URL} | grep "Welcome"
+  #           then
+  #           # Change this to 0 after the job fails
+  #           return 0
+  #           else
+  #           return 1
+  #           fi
 
-            # export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+  #           # export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
             
-            # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
-            # # URL="http://mohamedlotfy45.com"
-            # if curl -s --head ${URL}
-            # then
-            #   echo "It worked!"
-            #   exit 0
-            # else
-            #   echo "Rolling Back"
-            #   exit 1
-            # fi
+  #           # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+  #           # # URL="http://mohamedlotfy45.com"
+  #           # if curl -s --head ${URL}
+  #           # then
+  #           #   echo "It worked!"
+  #           #   exit 0
+  #           # else
+  #           #   echo "Rolling Back"
+  #           #   exit 1
+  #           # fi
       
 #       # Here's where you will add some code to rollback on failure  
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
+  cloudfront-update:
+    docker:
+      - image: mohamedlotfy/aws-nodejs
+    steps:
+      - checkout
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
+              --stack-name InitialStack
 #       # Here's where you will add some code to rollback on failure  
 
 # cleanup:
@@ -345,9 +344,9 @@ workflows:
       #     requires: [run-migrations]
       # - deploy-backend:
       #     requires: [run-migrations]
-      - smoke-test
+      # - smoke-test
       #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
+      - cloudfront-update
       #     requires: [smoke-test]
       # - cleanup:
       #     requires: [cloudfront-update]
