pushing all

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -47,6 +47,7 @@ jobs:
             cd frontend
             npm install
             npm run build
+            exit 1
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -64,6 +65,7 @@ jobs:
              cd backend
              npm install
              npm run build
+             exit 1
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -129,173 +131,173 @@ jobs:
             npm audit fix --force --audit-level=critical
             npm audit --audit-level=critical
 
-  # deploy-infrastructure:
-  #   docker:
-  #     - image: amazon/aws-cli
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           yum install -y tar gzip
-  #     - run:
-  #         name: Ensure back-end infrastructure exists
-  #         command: |
-  #           aws cloudformation deploy --template-file .circleci/files/backend.yml --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  --tags project=udapeople
-      # - run:
-      #     name: Ensure front-end infrastructure exist
-      #     command: |
-      #       aws cloudformation deploy \
-      #         --template-file .circleci/files/frontend.yml \
-      #         --tags project=udapeople \
-      #         --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-      #         --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+  deploy-infrastructure:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            yum install -y tar gzip
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy --template-file .circleci/files/backend.yml --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  --tags project=udapeople
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
+              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
           
-      # - run:
-      #     name: Add back-end ip to ansible inventory
-      #     command: |
-      #       aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
-      # - persist_to_workspace:
-      #     root: ~/
-      #     paths:
-      #       - project/.circleci/ansible/inventory.txt
-      # - destroy-environment      
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      - destroy-environment      
 
-  # configure-infrastructure:
-  #   docker:
-  #     - image: mohamedlotfy/aws-nodejs
-  #   steps:
-  #     - checkout
-  #     - add_ssh_keys:
-  #         fingerprints: ["0e:d9:d8:0a:3f:5f:e7:a4:d0:00:83:a5:fb:39:f8:50"]
-  #     # - attach_workspace:
-  #     #     at: ~/    
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           sudo apt -y install ansible gzip openssh-client
-  #     - run:
-  #         name: Configure server
-  #         command: |
-  #           cd .circleci/ansible
-  #           ansible-playbook -i inventory.txt configure-server.yml
-      # Here's where you will add some code to rollback on failure      
+  configure-infrastructure:
+    docker:
+      - image: mohamedlotfy/aws-nodejs
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints: ["0e:d9:d8:0a:3f:5f:e7:a4:d0:00:83:a5:fb:39:f8:50"]
+      # - attach_workspace:
+      #     at: ~/    
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt -y install ansible gzip openssh-client
+      - run:
+          name: Configure server
+          command: |
+            cd .circleci/ansible
+            ansible-playbook -i inventory.txt configure-server.yml
+      Here's where you will add some code to rollback on failure      
 
-  # run-migrations:
-  #   docker:
-  #     - image: mohamedlotfy/aws-nodejs
-  #   steps:
-  #     - checkout
-  #     - restore_cache:
-  #         keys: [backend-build]
-  #     - add_ssh_keys:
-  #         fingerprints: ["0e:d9:d8:0a:3f:5f:e7:a4:d0:00:83:a5:fb:39:f8:50"]
-  #     - run:
-  #         name: Run migrations
-  #         command: |
-  #           echo $TYPEORM_HOST
-  #           echo $TYPEORM_USERNAME
-  #           cd backend
-  #           npm install
-  #           npm run premigrations
-  #           npm run migrations
+  run-migrations:
+    docker:
+      - image: mohamedlotfy/aws-nodejs
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - add_ssh_keys:
+          fingerprints: ["0e:d9:d8:0a:3f:5f:e7:a4:d0:00:83:a5:fb:39:f8:50"]
+      - run:
+          name: Run migrations
+          command: |
+            echo $TYPEORM_HOST
+            echo $TYPEORM_USERNAME
+            cd backend
+            npm install
+            npm run premigrations
+            npm run migrations
 
-      # - run:
-      #     name: Send migration results to memstash
-      #     command: |
-      #       # Your code here.
-      #       exit 1
-#      # Here's where you will add some code to rollback on failure.      
+      - run:
+          name: Send migration results to memstash
+          command: |
+            # Your code here.
+            exit 1
+     # Here's where you will add some code to rollback on failure.      
 
-  # deploy-frontend:
-  #   docker:
-  #     - image: mohamedlotfy/aws-nodejs
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Deploy Frontend
-  #         command: |
-  #           export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-  #            echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" 
+  deploy-frontend:
+    docker:
+      - image: mohamedlotfy/aws-nodejs
+    steps:
+      - checkout
+      - run:
+          name: Deploy Frontend
+          command: |
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+             echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" 
             
-  #           cd frontend
-  #           echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" > .env
-  #           npm install
-  #           npm run build:prod
-  #           aws s3 cp dist s3://udapeople-789bbc4 --recursive
+            cd frontend
+            echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" > .env
+            npm install
+            npm run build:prod
+            aws s3 cp dist s3://udapeople-789bbc4 --recursive
 
-      # Here's where you will add some code to rollback on failure      
+      Here's where you will add some code to rollback on failure      
                     
-  # deploy-backend:
-  #   docker:
-  #     - image: mohamedlotfy/aws-nodejs
-  #   steps:
-  #     - checkout
-  #     - add_ssh_keys:
-  #         fingerprints: ["0e:d9:d8:0a:3f:5f:e7:a4:d0:00:83:a5:fb:39:f8:50"]
-  #     # attach workspace
-  #     - run:
-  #         name: Deploy backend
-  #         command: |
-  #           # export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-  #           # echo $TYPEORM_HOST >> .circleci/ansible/inventory.txt
+  deploy-backend:
+    docker:
+      - image: mohamedlotfy/aws-nodejs
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints: ["0e:d9:d8:0a:3f:5f:e7:a4:d0:00:83:a5:fb:39:f8:50"]
+      # attach workspace
+      - run:
+          name: Deploy backend
+          command: |
+            # export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            # echo $TYPEORM_HOST >> .circleci/ansible/inventory.txt
 
-  #           cd backend
-  #           npm i
-  #           npm run build
-  #           tar -czf artifact.tar.gz dist/* package*
-  #           cp artifact.tar.gz ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
-  #           ls ../.circleci/ansible/roles/deploy/
-  #           cd ../.circleci/ansible
-  #           ansible-playbook -i inventory.txt deploy-backend.yml
-#       # Here's where you will add some code to rollback on failure  
+            cd backend
+            npm i
+            npm run build
+            tar -czf artifact.tar.gz dist/* package*
+            cp artifact.tar.gz ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
+            ls ../.circleci/ansible/roles/deploy/
+            cd ../.circleci/ansible
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      # Here's where you will add some code to rollback on failure  
 
-  # smoke-test:
-  #   docker:
-  #     - image: amazon/aws-cli 
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           URL="http://udapeople-789bbc4.s3-website-us-east-1.amazonaws.com/#/employees"            
-  #           echo ${URL} 
-  #           if curl -s ${URL} | grep "Welcome"
-  #           then
-  #           # Change this to 0 after the job fails
-  #           return 0
-  #           else
-  #           return 1
-  #           fi
+  smoke-test:
+    docker:
+      - image: amazon/aws-cli 
+    steps:
+      - checkout
+      - run:
+          name: Backend smoke test.
+          command: |
+            URL="http://udapeople-789bbc4.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+            # Change this to 0 after the job fails
+            return 0
+            else
+            return 1
+            fi
 
-  #           # export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            # export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
             
-  #           # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
-  #           # # URL="http://mohamedlotfy45.com"
-  #           # if curl -s --head ${URL}
-  #           # then
-  #           #   echo "It worked!"
-  #           #   exit 0
-  #           # else
-  #           #   echo "Rolling Back"
-  #           #   exit 1
-  #           # fi
+            # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            # # URL="http://mohamedlotfy45.com"
+            # if curl -s --head ${URL}
+            # then
+            #   echo "It worked!"
+            #   exit 0
+            # else
+            #   echo "Rolling Back"
+            #   exit 1
+            # fi
       
-#       # Here's where you will add some code to rollback on failure  
+      # Here's where you will add some code to rollback on failure  
 
-  # cloudfront-update:
-  #   docker:
-  #     - image: mohamedlotfy/aws-nodejs
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Update cloudfront distribution
-  #         command: |
-  #           aws cloudformation deploy \
-  #             --template-file .circleci/files/cloudfront.yml \
-  #             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
-  #             --stack-name InitialStack
-#       # Here's where you will add some code to rollback on failure  
+  cloudfront-update:
+    docker:
+      - image: mohamedlotfy/aws-nodejs
+    steps:
+      - checkout
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
+              --stack-name InitialStack
+      # Here's where you will add some code to rollback on failure  
 
 # cleanup:
 #     docker:
@@ -330,23 +332,22 @@ workflows:
            requires: [build-backend]
       - scan-frontend:
            requires: [build-frontend]
-      # - deploy-infrastructure:
-      #       requires: [build-frontend]
-      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      #     filters:
-      #       branches:
-      #         only: [test-feature-branch]
-      # - configure-infrastructure
-          # requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
-      # - deploy-frontend
-      #     requires: [run-migrations]
-      # - deploy-backend:
-      #     requires: [run-migrations]
-      # - smoke-test
-      #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update
-      #     requires: [smoke-test]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [test-feature-branch]
+      - configure-infrastructure
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test
+          requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update
+          requires: [smoke-test]
       # - cleanup:
       #     requires: [cloudfront-update]
